version: '3.8'
services:
  db:
    container_name: pg_container_rd
    image: library/postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_rd
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  dgc-revocation-distribution-service:
    build: .
    image: eu-digital-green-certificates/dgc-revocation-distribution
    volumes:
      - ./certs:/ec/prod/app/san/dgc
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=gateway
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DGC_GATEWAY_CONNECTOR_ENDPOINT=https://dgc-gateway.example.com
      - DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH=file:/ec/prod/app/san/dgc/tls_trust_store.p12
      - DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PASSWORD=set_password_here
      - DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_ALIAS=1
      - DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH=file:/ec/prod/app/san/dgc/tls_key_store.p12
      - DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PASSWORD=set_password_here
      - DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_ALIAS=ta
      - DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PATH=file:/ec/prod/app/san/dgc/trust_anchor.jks
      - DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PASSWORD=set_password_here
      - DGC_ISSUANCE_DGCI_ENDPOINT=https://dgca-issuance-service-eu-test.example.com

    depends_on:
      - db
