server:
  port: 8080
spring:
  application:
    name: dgca-revocation-distribution-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dgc;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:db/changelog.xml
    database-change-log-table: RD_CHANGELOG
    database-change-log-lock-table: RD_CHANGELOG_LOCK
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 5
management:
  server:
    ssl:
      enabled: false
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health
    jmx:
      exposure:
        include: info,health
  health:
    probes:
      enabled: true

info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger

dgc:
  revocationListDownload:
    timeInterval: 1800000
    lockLimit: 3600000