logging:
  level:
    eu.europa.ec.dgc: INFO
    default: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
server:
  port: 8080
spring:
  application:
    name: dgca-revocation-distribution-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 2000
        order_inserts: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog.xml
    database-change-log-table: RD_CHANGELOG
    database-change-log-lock-table: RD_CHANGELOG_LOCK
  task:
    scheduling:
      pool:
        size: 5

management:
  server:
    ssl:
      enabled: false
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health
    jmx:
      exposure:
        include: info,health
  health:
    probes:
      enabled: true

info:
  name: ${spring.application.name}
  profiles: ${spring.profiles.active}
springdoc:
  api-docs:
    path: /api/docs
    enabled: true
    writer-with-order-by-keys: true
  swagger-ui:
    path: /swagger
    tagsSorter: alpha
    operationsSorter: alpha


dgc:
  revocationListDownload:
    timeInterval: 1800000
    lockLimit: 14400000
    downloadLimit: 90000 #max download time should be less than timeInterval
  defaultRevocationDataType: BLOOMFILTER  # Possible values are BLOOMFILTER and VARHASHLIST
  bloomFilter:
    enabled: true
    version: 1.0
    probRate: 0.000000000001f
  varHashList:
    enabled: true
    version: 1.0
    probRate: 0.000000000001f
    minByteCount: 4

  issuance:
    dgci:
      endpoint: ${DGC_ISSUANCE_DGCI_ENDPOINT}