dgc:
  gateway:
    connector:
      enabled: true
      endpoint: ${DGC_GATEWAY_CONNECTOR_ENDPOINT}
      proxy:
        enabled: false
      max-cache-age: 300
      tls-trust-store:
        password: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSTRUSTSTORE_PATH}
      tls-key-store:
        alias: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TLSKEYSTORE_PATH}
      trust-anchor:
        alias: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_ALIAS}
        password: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PASSWORD}
        path: ${DGC_GATEWAY_CONNECTOR_TRUSTANCHOR_PATH}